export const panelsTree: Record<string, string[]> = {
  content: ['badge', 'divider', 'icon', 'image', 'header', 'text', 'userpic'],
  controls: [
    'attach',
    'button',
    'buttonGroup',
    'checkbox',
    'menu',
    'radioButton',
    'radioBox',
    'textarea',
    'textinput',
    'tumbler',
    'select',
  ],
  layout: ['listTile', 'spacer'],
  navigation: ['link', 'tabsMenu'],
  progress: ['progress', 'spin'],
  surface: ['drawer', 'messageBox', 'modal', 'popup', 'tabsPanes', 'tooltip'],
}
